Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.0
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.1
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.2
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.3
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.4
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.5
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.6
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.7
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.8
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.9
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.10
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.11
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.12
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.13
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.14
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.15
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.16
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.17
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.18
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.19
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.20
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.21
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.22
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.23
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.24
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.25
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.26
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.27
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.28
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.29
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.30
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.31
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.32
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.33
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.34
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.35
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.36
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.37
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.38
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.39
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.40
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.41
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.42
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.43
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.44
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.45
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.46
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.47
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.48
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.49
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.50
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.51
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.52
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.53
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.54
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.55
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.56
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.57
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.58
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.59
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.60
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.61
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.62
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.63
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.64
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.65
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.66
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.67
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.68
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.69
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.70
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.71
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.72
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.73
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.74
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.75
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.76
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.77
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.78
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.79
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.80
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.81
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.82
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.83
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.84
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.85
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.86
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.87
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.88
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.89
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.90
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.91
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.92
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.93
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.94
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.95
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.96
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.97
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.98
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 138, in <module>
    model = init_model(model_str, max_iter, random_state)
  File "/global/homes/m/mphagen/functional-connectivity/model-fc/src/model_fc/models.py", line 115, in init_model
    return model
           ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value
srun: error: nid006643: task 0: Exited with exit code 1
srun: Terminating StepId=41617450.99
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.100
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.101
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.102
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.103
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.104
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.105
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.106
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.107
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.108
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.109
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.110
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.111
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.112
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.113
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.114
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.115
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.116
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.117
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.118
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.119
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.120
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.121
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.122
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.123
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.124
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.125
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.126
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS] [--n_trs N_TRS]
                  [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile] [--fc_data_path FC_DATA_PATH]
                  [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006643: task 0: Exited with exit code 2
srun: Terminating StepId=41617450.127
